### ISSUE TITLE
Reading the filterbank header fails when unexpected parameters are used

### ISSUE THREAD

**Issue by mmalenta** [AstroAccelerateOrg/astro-accelerate#114]
**Issue Summary**
get_file_data function does not ignore the unexpected fields properly, which in certain cases can lead to execution either hanging at the header read stage or failing during the execution.

**Steps to Reproduce**
This depends on the combination of header parameters used and the values they contain. Majority of non-simulated files that contain SIGRPOC filterbank parameters not explicitly included in the get_file_data function (for example machine_id and telescope_id)  will not be processed properly.

**Expected Outcome**
File to be processed properly and all the header parameters printed out correctly with debugging messages.

**Actual Outcome**
Execution hanging / failing, proper information missing form the debugging print statements with the contents of the filterbank header, such as:

12	HEADER_START
11	source_name
4	FAKE
10	machine_id <-- **goes wrong here**
10	

5	ibeam <-- **recovers here, but important information including channel and frequency information is lost**
6	tstart
5	tsamp
4	nifs
10	HEADER_END

In this case machine_id is set to 10, and instead of being read as such, the reader function interprets it as the next parameter in line having 10 characters, resulting in incorrect information being read.

**Configuration**
Using filterbank files with unprocessed SIGPROC header parameters set to values different than 0 - setting them to 0 (aka FAKE) will not cause these problems and the reading routine will simply skip to the next value. This problem does not come up with simulated files as they usually have all the unprocessed parameters set to 0.

**Notes**
This can be solved by either including the remaining header parameters, to be more compliant with SIGPROC conventions or just ignoring them properly as they are not being used anywhere at the moment.

**Comment by KAdamek** [comment]
Fixed some time ago by adding header parameters and added detection for the end of the header.
