### ISSUE TITLE
Optimize getting number of samples in fil file

### ISSUE THREAD

**Issue by KAdamek** [AstroAccelerateOrg/astro-accelerate#118]
**Affected feature**
Reading files.

**Description of the optimisation**
Currently to get number of samples AA reads whole fil file after header. This is slow. Better way is to jump at the end of the file and compute number of samples from position of the "end of file". Branch code_cleaning has this implemented already. We should also check if header contains number of samples. We could also check if this agree with calculated number of samples

**Why it should be better**
Because AA would not read whole file just to get number of samples.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No

Expected semantic version number increment category (Please indicate x.y.z): z

**Notes**

**Comment by ccarels** [comment]
Closed via #120.
