### ISSUE TITLE
FDAS segfolds

### ISSUE THREAD

**Issue by KAdamek** [AstroAccelerateOrg/astro-accelerate#137]
**Issue Summary**
FDAS segfolds when run.

**Steps to Reproduce**

**Expected Outcome**

**Actual Outcome**

**Configuration**

**Notes**

**Comment by ccarels** [comment]
@KAdamek I can take a look at this. For reproducibility, could you provide the machine and GPU card details, the configuration of params.hpp, the commit hash of the branch (assuming no uncommitted changes), the input file and data file, and a crash log, please?

**Comment by ccarels** [comment]
There may be multiple things at play here, but I'm a bit concerned by pull request #135 in relation to this issue (I made a number of comments there.)

**Comment by ccarels** [comment]
These issues should now be fixed on the master branch.
