### ISSUE TITLE
Add summary of module inputs/outputs

### ISSUE THREAD

**Issue by KAdamek** [AstroAccelerateOrg/astro-accelerate#138]
**Description**
Add description of modules output to wiki

**Outcome**
Better documention

**Timeline**

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No

Expected semantic version number increment category (Please indicate x.y.z):

**Notes**

**Comment by ccarels** [comment]
@KAdamek I will summarise this separately in a top-level document that outlines the API and the main modules and how to use it. Wiki documentation does not get automatically updated when code changes, whereas documentation generated from code comments does - I am documenting the module inputs and outputs in the code. I will adjust the issue title accordingly.

**Comment by ccarels** [comment]
Subsumed under cc_pipeline_interfaces.

**Comment by ccarels** [comment]
In fact, I already created this issue as issue #63, so I will close this issue as a duplicate. Further comments should be addressed in issue #63.
