### ISSUE TITLE
Unit test exiting - error in one stops execution of all other unit tests

### ISSUE THREAD

**Issue by chrisjwilliams** [AstroAccelerateOrg/astro-accelerate#15]
Running the unit tes executable for astro-accelerate results in an exit. 
This stops ALL other unit tests running.

```
⟫ ./lib/astro-accelerate/test/gtest_AstroAccelerate 
[==========] Running 2 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from AstroAccelerateTest
[ RUN      ] AstroAccelerateTest.AstroAccelerate_call
Need input file.
```

It should run all other unit tests.

**Comment by NassimOuannoughi** [comment]
That's probably because this test expects an input file as a command-line argument. I commented that out, it should work now.

**Comment by chrisjwilliams** [comment]
It now runs all the tests. Fixing failing tests by excluding them is a novel QA approach though!

**Comment by NassimOuannoughi** [comment]
This test was using some of the functions from the standalone astro-accelerate to provide input data. The one which caused the code to exit is get_user_input(...) which expects a command-line argument. If it's not provided, the code exit. You either provide a command-line argument here or you don't run this test ...
