### ISSUE TITLE
AstroAccelerate run_astroaccelerate_sps calls are thread-unsafe

### ISSUE THREAD

**Issue by ewanbarr** [AstroAccelerateOrg/astro-accelerate#18]
As it currently stands, the main run_astroaccelerate_sps method is unsafe to use in a multi-GPU environment. This is due to class attributes on the associated AstroAccelerate object being set inside the call. 

Currently we have a work around that creates a new AstroAccelerate object for each call to each GPU, but this results in unnecessary overheads. 

An example of a thread-unsafe portion of the code is the _inc variable which is updated in a loop. This variable is used to determine the start point when reading from a buffer. Thread conflicts here can easily result in out-of-bounds memory accesses.

**Comment by ccarels** [comment]
Subsumed under cc_pipeline_interfaces.
