### ISSUE TITLE
Error: missing fdas_test_parameters.h

### ISSUE THREAD

**Issue by krajwade** [AstroAccelerateOrg/astro-accelerate#20]
I am currently building the cheetah pipeline via a docker container. When compiling astro-accelerate, I used the following command:

RUN cd /software/astro-accelerate/ && \
    git checkout aa_interface && \
    mkdir build/ && \
    cd build/ && \
    cmake -DENABLE_CUDA=true ../ && \
    make -j 16 && \
    make install

and I am getting the following error after make install:

CMake Error at lib/cmake_install.cmake:57 (file):
  file INSTALL cannot find
  "/software/astro-accelerate/lib/headers/fdas_test_parameters.h".
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)
  Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1

Has anyone seen this before. I checked the aa_interface branch and there is no such header file.

**Comment by KAdamek** [comment]
Hi,
the header file 'fdas_test_parameters.h' is in master branch of AstroAccelerate and it defines some test parameters for FDAS test using accelerated sin wave. I'm not sure why it is required by aa_interface branch unless someone has updated it from master branch.

**Comment by ewanbarr** [comment]
For some reason it looks like the git checkout might not be working properly on the specific machine Kaustubh is using. I can't replicate this and I have tried it on a couple of machines with the same Dockerfile.

**Comment by krajwade** [comment]
So I have built the pipeline now. The only way to do that was to manually clone the astro-accelerate repo and then build it. If I clone through the Dockerfile, it does not work.

**Comment by ewanbarr** [comment]
This is a very strange error. I suspect it is something to do with the
permissions setup on your docker which causes an issue when try to alter a
previous layer in the image. Can I suggest a quick fix, put the git clone
for AstroAccelerate in the same docker RUN command and delete the earlier
one:

RUN git clone <AstroAccelerate uri>
cd /software/astro-accelerate/ &&
git checkout aa_interface &&
mkdir build/ &&
cd build/ &&
cmake -DENABLE_CUDA=true ../ &&
make -j 16 &&
make install

**Comment by krajwade** [comment]
That worked as well.
