### ISSUE TITLE
Dedispersion for number of channels > 16k

### ISSUE THREAD

**Issue by KAdamek** [AstroAccelerateOrg/astro-accelerate#201]
**Description**
Dedispersion cannot process more then 16k frequency channels. This is caused by limitation of constant memory.

**Outcome**
Allow dedispersion to process more then 16k frequency channels

**Timeline**

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No

Expected semantic version number increment category (Please indicate x.y.z):y

**Notes**

**Comment by jan2nov** [comment]
Solved in #203
