### ISSUE TITLE
Incomplete data in return from AstroAccelerate::run_dedispersion_sps()

### ISSUE THREAD

**Issue by griffinfoster** [AstroAccelerateOrg/astro-accelerate#21]
the output_sps vector passed into this function only fills the first two floats (time, dm), the other params are never set (width, snr).

lib/astro-accelerate/detail/AstroAccelerate.cp line 240

**Comment by KAdamek** [comment]
This is where candidates coordinates are transformed from array indices to time and DM. Candidate width and SNR is at that point in the code already set at:
astro-accelerate / lib / device_threshold_kernel.cu 35
or
astro-accelerate / lib / device_peak_find_kernel.cu 251

**Comment by griffinfoster** [comment]
so this information needs to propagate to the run_despersion_sps output so we can see it.

**Comment by KAdamek** [comment]
I do not understand what do you mean. The width and SNR of the candidate does not need to be transformed in any way as such they are left in the output as they are. The piece of code you are referring to performs some function on elements of the candidate array and writes into same array.

**Comment by griffinfoster** [comment]
I mean that the width and SNR are not being passed back out through the interface. You may think that you are filling them in your code, but we do not receive them at our end. Could you please comment on line 240 of lib/astro-accelerate/detail/AstroAccelerate.cp? The first two elements are filled. The last two are left empty.

**Comment by KAdamek** [comment]
OK. Code on line 240 is mapping between same indices on the same array. There is no need to explicitly write 
output_sps[4*count + 2] = output_sps[4*count + 2];  //SNR
output_sps[4*count + 3] = output_sps[4*count + 3]; // width
as it would do nothing. That is they are not left empty they are left as they are. If SNR and width are not in the output it is not because of code on line 240.

**Comment by griffinfoster** [comment]
Ok, that's useful. However, could you check that wherever width and SNR are filled for the output, it is done properly? Is this tested in some way? Width is reported as 1000 for our tests.

**Comment by KAdamek** [comment]
OK, I'll look into it and see what might be the problem. In the mean time I would suggest using AstroAccelerate master.

**Comment by griffinfoster** [comment]
That sounds great. So master is now synced to this branch and we can just change over without any changes? If so yes I think that's a good idea.

**Comment by KAdamek** [comment]
Unfortunately, current standalone code which is AstroAccelerate master is not easily changed to what cheetah expects. At least I do not know easy way how to do that.
