### ISSUE TITLE
Dedispersion kernel not launching

### ISSUE THREAD

**Issue by jan2nov** [AstroAccelerateOrg/astro-accelerate#214]
**Issue Summary**
AstroAccelerate behaves as normal, except the de-dispersion kernel got call error and did not trigger at all. It especially occurs with certain autotune parameters

**Steps to Reproduce**
Maybe the same behaviour will be when asking for more shared memory than it is available on the card

**Expected Outcome**
Stop and inform user with an appropriate error

**Actual Outcome**
Run without warnings. At the end the de-dispersion kernel took 0 ms.

**Configuration**

**Notes**

**Comment by KAdamek** [comment]
Solved. The CUDA error did not propagate back to the pipeline.
