### ISSUE TITLE
Can astro-accelerate run on a A100 GPU (Ampere architecture) ?

### ISSUE THREAD

**Issue by astro-sjgao** [AstroAccelerateOrg/astro-accelerate#270]
Information of my GPU is as follows:
NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4

**Comment by jan2nov** [comment]
Hello, 

yes AstroAccelerate can run on A100 architecture. During the launching of _cmake_ you just need to pass the right cuda capability 8.0:


```
> mkdir build
> cmake -DCUDA_ARCH="8.0" ../
> make
```

This way you should be able to run AstroAccelerate on A100 GPU.

**Comment by jan2nov** [comment]
Closed
