### ISSUE TITLE
Build for AA

### ISSUE THREAD

**Issue by KAdamek** [AstroAccelerateOrg/astro-accelerate#28]
Add support for install target

make install - should ensure the library is build and put the build products in their rightful place.
library into       ${prefix}/lib
include into       ${prefix}/include/astroaccelerate
documentation into ${prefix}/share/astroaccelerate/doc
support tools      ${prefix}/share/astroaccelerate/tools
where 'prefix' is desired install destination.

**Comment by celestian** [comment]
I propose to use https://en.wikipedia.org/wiki/GNU_Build_System , aka autotools
I think I could try to prepare patch during weekend.

But, I have one question. On which Linux distribution (and which version) are you developing? Or which Linux distribution, and their versions, are supported?

**Comment by celestian** [comment]
@KAdamek , any proposal to answer above? :-)

**Comment by KAdamek** [comment]
As far as I know, it is Fedora and Ubuntu.

**Comment by ccarels** [comment]
Subsumed under #100 where CMake is used.

**Comment by celestian** [comment]
@ccarels  Thanks for this effort.
