### ISSUE TITLE
CARD compile constant not needed

### ISSUE THREAD

**Issue by jsharpe** [AstroAccelerateOrg/astro-accelerate#3]
The device that is used can be controlled by setting CUDA_VISIBLE_DEVICES so if you always set the device used to 0 you can control which card is used by setting this environment variable before running.

See https://devblogs.nvidia.com/parallelforall/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/

**Comment by NassimOuannoughi** [comment]
Thanks for the link, that's an interesting option.
CARD compile constant will be removed and become an user parameter for the interface: "device_id" (our CARD). In the SKA pipeline, it is requested to have it since SKA will assign tasks to devices, we have no control over it. A "normal" user could pass his device id manually.

**Comment by jsharpe** [comment]
Is there any design documentation around the pipeline? 
The reason I ask is that due to the date rates that will be ingested into the module in the final solution I would expect there to be a dedicated 1-1 mapping of the data feed to a given gpu. I believe that the unpacking of the received from the spead2 library(http://spead2.readthedocs.io/en/latest/) should be done directly into the memory that will be used for the GPU processing in this library. As such I'd see dynamic allocation of GPUs to these feeds would introduce an unnecessary copy and reformatting of the data which is just wasting host memory bandwidth which at the desired data rates will be limited.

**Comment by jsharpe** [comment]
For more details on such an approach see the nvidia presentation here: http://on-demand.gputechconf.com/gtc/2015/presentation/S5412-Davide-Rossetti.pdf

**Comment by NassimOuannoughi** [comment]
https://gitlab.com/SKA-TDT/cheetah

This is the gitlab repository of the pipeline.

**Comment by jsharpe** [comment]
Thanks, I don't appear to have access to that repository though.
