### ISSUE TITLE
Remove large files

### ISSUE THREAD

**Issue by ccarels** [AstroAccelerateOrg/astro-accelerate#35]
---
name: Feature Request
about: Make a feature request to help us improve

---

**Description**
Several large files are in the repository history.
These look like they can be safely removed from the repository history. Removing them will likely greatly reduce the repository size (currently ~20 MB).
This will reduce the time needed to clone the repository.

**Outcome**
A smaller repository.

**Timeline**
As soon as convenient.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No.

Expected semantic version number increment category (Please indicate x.y.z): z.

**Notes**

| Git Hash | Size [bytes] | Path |
|----------|----------|----------|
7a3e7bae24582efe205f90836ec7d5d68f2745ff | 1378840 | build/dedisperse-gpu
5b762a04f6ead030d1f09f665d656bc2dd1ba945 | 1379120 | build/dedisperse-gpu
98fe4f4dcba17de02497af2121883f108a7c6634 | 1595992 | astrolib/libastrolib.a
b13e78e481aace5b1871fcdb30d11e555227479c | 1596360 | astrolib/libastrolib.a
0ab45b02317c7c7a66c5b0a101c33466914c1c74 | 1642684 | astrolib/libastrolib.a
c1e53623c8d8106a347f9f71313e065bc13f3bf6 | 1648002 | astrolib/libastrolib.a
c6b3a3015029e3432f9447a065aa9988e3209fa4 | 1670068 | astrolib/libastrolib.a
25c87e3aa993c6a26674d461150f5d7a9309c0a8 | 1707620 | astrolib/libastrolib.a
1cdaa6726fdaf552427f5a5c5be9db184a000f9a | 1708684 | astrolib/libastrolib.a
3ac417c81a541fae7fec141378e258a846c19084 | 2334346 | output/ska_karel/global_analysed_frb.dat
842a639f5999ef921a3303393acdc9c39731ef63 | 4983646 | astrolib/libastrolib.a
8ceb07741645c66a2fdbc52fd8982ab2426e3bd3 | 4985782 | astrolib/libastrolib.a
b3d44079ed1f58cb3cd8f6eddad242ca19fa5506 | 5154742 | astrolib/libastrolib.a
7d58b160ba66e6451f8fca76b64865ebd0bf6476 | 5329922 | astrolib/libastrolib.a
8dc5fa68eea9a0d439741c77564e164ffa3805c7 | 5331180 | astrolib/libastrolib.a
01b19cab3155ef90ee092ab04f0e35e4793965b9 | 5332954 | astrolib/libastrolib.a
ca93011e354642a01ca331c0c54622c75838aba2 | 5495602 | astrolib/libastrolib.a
777bef3bf7be0564885066ccf70d3d7bdfe76b1a | 5679988 | astrolib/libastrolib.a
3c551f24d65433726a87c6ddc42a30f4590e5c64 | 5948400 | astrolib/libastrolib.a
6da136e45c5493f1b0494f9425c1d46664707ff4 | 6409622 | astrolib/libastrolib.a
68ad848854be0df38707babf4e583c4f5c51eb03 | 6411278 | astrolib/libastrolib.a
5b687580e7cb5313203bc08551c8ba8336d064f6 | 9265956 | astrolib/libastrolib.a
cf1367d491b1550092d37834b7f9050857fbc344 | 9351644 | astrolib/libastrolib.a
a585a902c21b3aeb8298fffbba4c4848259cb5c5 | 11095766 | lib/out.txt.filepart

**Comment by wesarmour** [comment]
Ok :)

**Comment by ccarels** [comment]
I have demonstrated the result in a forked repository: https://github.com/ccarels/astro-accelerate (temporary link).
The newer repository size is considerably smaller.
However, since changing the history is quite drastic, let's first review the differences carefully and then decide whether to proceed in this repository.

**Before: 20,661,409 bytes (~20.7 MB)**
**After: 7,017,204 bytes (~7 MB)**.

**Comment by ccarels** [comment]
Following no objections at the group meeting, I'll proceed with this. I'll also make an offline backup of the repository before and after, in case it is ever of interest.

**Comment by ccarels** [comment]
The following were removed from the history

| Git Hash | Size [bytes] | Description |
| ------ | ------ | ------ |
| 5b762a04f6ead030d1f09f665d656bc2dd1ba945 | 1379120 | dedisperse-gpu |
| 7a3e7bae24582efe205f90836ec7d5d68f2745ff | 1378840 | dedisperse-gpu |
| 3ac417c81a541fae7fec141378e258a846c19084 | 2334346 | global_analysed_frb.dat |
| 7d58b160ba66e6451f8fca76b64865ebd0bf6476 | 5329922 | libastrolib.a |
| 98fe4f4dcba17de02497af2121883f108a7c6634 | 1595992 | libastrolib.a |
| 6da136e45c5493f1b0494f9425c1d46664707ff4 | 6409622 | libastrolib.a |
| 25c87e3aa993c6a26674d461150f5d7a9309c0a8 | 1707620 | libastrolib.a |
| c1e53623c8d8106a347f9f71313e065bc13f3bf6 | 1648002 | libastrolib.a |
| c6b3a3015029e3432f9447a065aa9988e3209fa4 | 1670068 | libastrolib.a |
| 5df779379aefd0364b4f0bc54d74f1f31f6c64e3 | 1689354 | libastrolib.a |
| 68ad848854be0df38707babf4e583c4f5c51eb03 | 6411278 | libastrolib.a |
| b3d44079ed1f58cb3cd8f6eddad242ca19fa5506 | 5154742 | libastrolib.a |
| e7bd432a41443faa3e35644731c349ced32d663c | 1673330 | libastrolib.a |
| cff6eb309c67f298e14ce3da9ffb4a9fdc3407ed | 1665660 | libastrolib.a |
| cf1367d491b1550092d37834b7f9050857fbc344 | 9351644 | libastrolib.a |
| 777bef3bf7be0564885066ccf70d3d7bdfe76b1a | 5679988 | libastrolib.a |
| 0ab45b02317c7c7a66c5b0a101c33466914c1c74 | 1642684 | libastrolib.a |
| b13e78e481aace5b1871fcdb30d11e555227479c | 1596360 | libastrolib.a |
| 41709a147814f1e8f65399abcdc17ef99ec53433 | 2676142 | libastrolib.a |
| 35e5ccea3032ab33a198846453650e4e79dbaeb9 | 2608820 | libastrolib.a |
| 1cdaa6726fdaf552427f5a5c5be9db184a000f9a | 1708684 | libastrolib.a |
| ece36ee4848e5303bb5f6e7d2e6c1a2f61978971 | 1689354 | libastrolib.a |
| 8dc5fa68eea9a0d439741c77564e164ffa3805c7 | 5331180 | libastrolib.a |
| 5b687580e7cb5313203bc08551c8ba8336d064f6 | 9265956 | libastrolib.a |
| 8ceb07741645c66a2fdbc52fd8982ab2426e3bd3 | 4985782 | libastrolib.a |
| ca93011e354642a01ca331c0c54622c75838aba2 | 5495602 | libastrolib.a |
| 01b19cab3155ef90ee092ab04f0e35e4793965b9 | 5332954 | libastrolib.a |
| 114350dc10a7357c715cc937330a898289cf90fe | 1689354 | libastrolib.a |
| 4d5a2c1535b74f505278d6c0ffcf23d6fe8f3c7a | 2721650 | libastrolib.a |
| 3a751bff7c39843a1b7d784d194828efdfb1b796 | 1689354 | libastrolib.a |
| 1845f87087846e75db50d8cd9cfe3ebfe19887df | 1665692 | libastrolib.a |
| 3c551f24d65433726a87c6ddc42a30f4590e5c64 | 5948400 | libastrolib.a |
| 842a639f5999ef921a3303393acdc9c39731ef63 | 4983646 | libastrolib.a |
| a585a902c21b3aeb8298fffbba4c4848259cb5c5 | 11095766 | out.txt.filepart |

**Comment by ccarels** [comment]
The new repository size is **6948 bytes (~ 6.9 MB)**.
