### ISSUE TITLE
Consider using CATCH instead of googletest framework

### ISSUE THREAD

**Issue by jsharpe** [AstroAccelerateOrg/astro-accelerate#4]
Catch is here: https://github.com/philsquared/Catch

**Comment by chrisjwilliams** [comment]
Why? What does it give you over and above googletest?

**Comment by jsharpe** [comment]
See: http://blog.coldflake.com/posts/Testing-C++-with-a-new-Catch/

It reduces the amount of setup needed and removes the needs for fixtures. It also supports a BDD style of testing and allows you to use C++ style comparisons in your assertions without needing to remember which of the ASSERT_* or EXPECT_* macros I need to use.

It also doesn't have the limitations in this post: http://stackoverflow.com/questions/17961900/why-does-google-test-assert-false-not-work-in-methods-but-expect-false-does which makes writing good quality tests harder as you get pushed into using certain design patterns in your function call design.

**Comment by chrisjwilliams** [comment]
Nice, definitely one to watch!
But its still pretty limited: no parametrised/typed testing or support for death tests.
