### ISSUE TITLE
Support for comments in input_files

### ISSUE THREAD

**Issue by ccarels** [AstroAccelerateOrg/astro-accelerate#50]
**Description**
Is there support to add comments in `input_files`?
If there isn't, I think this would be a really useful feature to have.

For example, looking at `https://github.com/AstroAccelerateOrg/astro-accelerate/blob/master/input_files/BenMeerKAT.txt`, it would be good if there is a way that the user can add comments and notes to the file.

**Outcome**
The ability to add comments in the input_files.

**Timeline**
When needed/As soon as possible.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No.

Expected semantic version number increment category (Please indicate x.y.z): z.

**Notes**
N/A.

**Comment by ccarels** [comment]
@KAdamek @jan2nov I have assigned the issue to myself for now, can you comment on the above and let me know?

**Comment by KAdamek** [comment]
Yes, I think comments in input/configuration files would be useful but it is a 'could have' feature. I think that this is sort of already in if you start the line with '-', but I'm not sure.

**Comment by ccarels** [comment]
I tried this out, looks like this already works.
