### ISSUE TITLE
Add script to set up CUDA environment

### ISSUE THREAD

**Issue by ccarels** [AstroAccelerateOrg/astro-accelerate#53]
**Description**
Adds environment variables to a new script `setup.sh`.

The first iteration will be to source the CUDA environment variables.

**Outcome**
User-friendly setup of environment variables.

**Timeline**
As soon as possible.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No.

Expected semantic version number increment category (Please indicate x.y.z): y.

**Notes**
N/A.

**Comment by KAdamek** [comment]
I think that we want a different approach to setting of cuda, which is probably easily dealt with cmake. We want to detect which cuda version is installed and change the make file accordingly so the -gencode arch=XX, code=XX but also other things reflects what is installed in the system and what GPU is present. I'm not good with bash so correct me if I'm wrong, but that is not what the setup seems to be doing. Jan could help you more regarding what CUDA is doing when it is installed, I do not know much about that.

**Comment by ccarels** [comment]
@KAdamek Thanks for the feedback. Correct, the script does not "auto detect" which CUDA version is installed.

As far as I'm aware, a CUDA library user needs to set `$PATH` and `$LD_LIBRARY_PATH` first, before being able to do CUDA function calls in a terminal as it looks like you're suggesting. (See https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#environment-setup)

My plan is to start moving the build system to CMake, this could subsume a portion of this script once that is done.

**Comment by jan2nov** [comment]
Yes, currently the script is not detecting which generation of cuda 
device you have and that is by user selected in the Makefile 
accordingly. I think you can compile with more generations and 
cuda_capabilities to create appropriate library version for each one but 
I never investigate that.

Nvidia quite change the way how it is installed and if they 
automatically setup the PATH and LD_LIBRARY_PATH. However best way is 
assuming the user need to set it (either in bash_profile, or bashrc, 
...). By default the cuda toolkit is installed (if the user during 
installing not changed it) in /usr/local/cuda-{version} and then is 
created a symbolic link to /usr/local/cuda to the newest version of the 
toolkit. Not sure where else is written the version of the cuda 
installed, usually I am just using nvcc --version.

**Comment by ccarels** [comment]
I think the point here is that the `makefile` does not work without `PATH` and `LD_LIBRARY_PATH` being set. Similarly, `nvcc --version` also does not work unless the user sets `PATH` and `LD_LIBRARY_PATH`. The `setup.sh` script is there to make the process more user-friendly.

By the sounds of it, we could use `/usr/local/cuda/` in `setup.sh` instead of `/usr/local/cuda-{version}`. I have edited cc_53_setupscript to reflect this.
