### ISSUE TITLE
CUDA 8.0 shuffle functions deprecation

### ISSUE THREAD

**Issue by KAdamek** [AstroAccelerateOrg/astro-accelerate#61]
**Description**
NVIDIA changed shuffle function calls in new CUDA 9. Old deprecated function calls creates warnings and might (will) be dicontinued in next CUDA version. Warning also make compilation unreadable.

**Outcome**
There is two ways of doing this. Either change all shuffle calls to a new format. That is change
__shfl(XX) -> __shfl_sync(mask,XX)
__shfl_up(XX) -> __shfl_up_sync(mask,XX)
__shfl_down(XX) -> __shfl_down_sync(mask,XX)
__shfl_xor(XX) -> __shfl_xor_sync(mask,XX)
This change will however break comatability with older version of CUDA.

Or create inline function :
`
__device__ __inline__ float shfl_xor(mask, XX){
	#if (CUDART_VERSION >= 9000)
		return(__shfl_xor_sync(mask, XX));
	#else
		return(__shfl_xor(XX));
	#endif
}
`
In case of FFT codes I have noticed no or marginal performance impact.

**Timeline**
Soonish but not critical

**Interfaces**
Will this feature result in a backwards-incompatible interface change:
Yes/no depending on method

Expected semantic version number increment category (Please indicate x.y.z):
No idea. First we should set some starting point.

**Notes**

**Comment by ccarels** [comment]
I will go for the second option, so as not to break backwards compatibility.

The compiler warns of the following deprecations:
`__shfl_up() is deprecated in favor of __shfl_up_sync()`
`__shfl_down() is deprecated in favor of __shfl_down_sync()`
`__ballot() is deprecated in favor of __ballot_sync()`
`__shfl() is deprecated in favor of __shfl_sync()`
`__shfl_xor() is deprecated in favor of __shfl_xor_sync()`
