### ISSUE TITLE
Purpose of device_dedispersion_kernel.orig

### ISSUE THREAD

**Issue by ccarels** [AstroAccelerateOrg/astro-accelerate#69]
**Description**
Is `device_dedispersion_kernel.orig` a duplicate of `device_dedispersion_kernel.cu`?

Are both of these to be compiled or just one?

**Outcome**
Clarification.

**Timeline**
As soon as possible.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No.

Expected semantic version number increment category (Please indicate x.y.z): z.

**Notes**
N/A.

**Comment by wesarmour** [comment]
The .orig is an old file that it’s used.

**Comment by ccarels** [comment]
Thanks, since it is not used, we'll keep `device_dedispersion_kernel.orig` in the repository but exclude it from the compilation process.
