### ISSUE TITLE
Consistent header guard naming convention

### ISSUE THREAD

**Issue by ccarels** [AstroAccelerateOrg/astro-accelerate#78]
**Description**
Make header guard naming convention consistent across the repository.

I will impose the convention that all header guards are named after their file name, prepended by `ASTRO_ACCELERATE` (for uniqueness), and appended with the file extension (to differentiate CUDA files from non-CUDA files, in case it is needed). For example, the file `device_msd.hpp` would have header guard `ASTRO_ACCELERATE_DEVICE_MSD_HPP`.

**Outcome**
Consistent header guard naming.

**Timeline**
As soon as needed.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No.

Expected semantic version number increment category (Please indicate x.y.z): z.

**Notes**
N/A.

**Comment by KAdamek** [comment]
OK that seems sensible.

**Comment by ccarels** [comment]
I have implemented this in branch cc_62_buildsystem.
