### ISSUE TITLE
Ordering of block and grid size arguments to kernels

### ISSUE THREAD

**Issue by ccarels** [AstroAccelerateOrg/astro-accelerate#80]
**Description**
It looks like some kernel function calls pass the block size argument before the grid size argument and sometimes vice versa. Is there a clear convention on the naming of variables and the order of the parameters for which the kernels are dimensioned?

**Outcome**
Clarification.

**Timeline**
N/A.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: N/A.

Expected semantic version number increment category (Please indicate x.y.z): N/A.

**Notes**
N/A.

**Comment by KAdamek** [comment]
If you mean configurating of the kernel then that is given by <<< nBlocks, nThreads >>>
Can you pointout examples of the functions in question?

**Comment by ccarels** [comment]
For example, look at `device_corner_turn.cu` on line 33
https://github.com/AstroAccelerateOrg/astro-accelerate/blob/d2abf60a7e6c9adbe0b14323a133678c4364d11e/lib/device_corner_turn.cu#L33

versus line 103
https://github.com/AstroAccelerateOrg/astro-accelerate/blob/d2abf60a7e6c9adbe0b14323a133678c4364d11e/lib/device_corner_turn.cu#L103

In the first case, the grid is dimensioned using `num_blocks` as the first argument, whereas in the second case the `blockSize` is the second argument. So, in one case the reference to blocks is in the first parameter, and in another case the reference to blocks is in the second parameter of the kernel function dimensioning.

**Comment by KAdamek** [comment]
There is no convention on this.

**Comment by ccarels** [comment]
The same applies to the dimensioning of the kernels in `device_harmonic_summing_kernel.cu`.
