### ISSUE TITLE
Arguments to MSD_BLN_grid_outlier_rejection kernel in device_MSD.cu

### ISSUE THREAD

**Issue by ccarels** [AstroAccelerateOrg/astro-accelerate#81]
**Description**
In `device_MSD.cu` on line 316
https://github.com/AstroAccelerateOrg/astro-accelerate/blob/d2abf60a7e6c9adbe0b14323a133678c4364d11e/lib/device_MSD.cu#L316

the first argument to the kernel call is `d_output`.

Yet, when I look at the definition of this kernel in `device_MSD_outlier_rejection_kernel.cu` on line 257
https://github.com/AstroAccelerateOrg/astro-accelerate/blob/d2abf60a7e6c9adbe0b14323a133678c4364d11e/lib/device_MSD_outlier_rejection_kernel.cu#L257

The first parameter is `float const* __restrict__ d_input`.

Is this as intended?

**Outcome**
Clarification. Potential bug fix.

**Timeline**
As soon as possible.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: N/A.

Expected semantic version number increment category (Please indicate x.y.z): z.

**Notes**
N/A.

**Comment by KAdamek** [comment]
After looking through the code I would say, naming of the variables is not very helpfull but data contained by these variables are correct.

**Comment by ccarels** [comment]
Without further knowledge or specific evidence of a bug, the question of this issue is clarified. Any new conventions on naming should be brought up in a separate dedicated issue.
