### ISSUE TITLE
Should the SNR module depend on the SPS module?

### ISSUE THREAD

**Issue by ccarels** [AstroAccelerateOrg/astro-accelerate#82]
**Description**
On line 10 of `device_SPS_inplace_kernel.cu`, see https://github.com/AstroAccelerateOrg/astro-accelerate/blob/6ca6d1e410fdb61b50510690d911fe40a624ac60/lib/device_SPS_inplace_kernel.cu#L10

there is a variable declaration
`__device__ __constant__ float c_sqrt_taps[PD_MAXTAPS + 1];`.

`grep` for "c_sqrt_taps" shows that the following source files depend on the existence of `c_sqrt_taps`

```
$ grep "c_sqrt_taps" ./*
device_load_data.cu:	cudaMemcpyToSymbol(c_sqrt_taps, h_sqrt_taps, ( PD_MAXTAPS + 1 ) * sizeof(float));
device_single_pulse_search.cu:	//cudaMemcpyToSymbol(c_sqrt_taps, h_sqrt_taps, (PD_MAXTAPS+1)*sizeof(float));
src/device_single_pulse_search_kernel.cu://__device__ __constant__ float c_sqrt_taps[PD_MAXTAPS + 1];
device_single_pulse_search_kernel.cu:		ftemp = c_sqrt_taps[f] * signal_sd;
device_SNR_limited_inplace_kernel.cu://__device__ __constant__ float c_sqrt_taps[PD_MAXTAPS+1];
device_SNR_limited_inplace_kernel.cu:		ftemp = c_sqrt_taps[f]*signal_sd;
device_SPS_inplace_kernel.cu:__device__ __constant__ float c_sqrt_taps[PD_MAXTAPS + 1];
device_SPS_inplace_kernel.cu: //ftemp = c_sqrt_taps[f]*signal_sd;
device_SPS_long_kernel.cu:	output.x = __fdividef( x , c_sqrt_taps[Taps] );
device_SPS_long_kernel.cu:	output.y = __fdividef( y , c_sqrt_taps[Taps] );
```

A few of them have the declaration commented out. It looks like the other files which use `c_sqrt_taps` depend on the declaration of `c_sqrt_taps` which is in `lib/device_SPS_inplace_kernel.cu`.

The dependence means that the `SNR` module depends on the existence of the `SPS` module.
Is it intended that the code shares the `c_sqrt_taps` variable, and that these modules depend on one another?

**Outcome**
Clarification.

**Timeline**
N/A.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: N/A.

Expected semantic version number increment category (Please indicate x.y.z): N/A.

**Notes**
N/A.

**Comment by KAdamek** [comment]
I believe that c_sqrt_taps is not used, or it should not be used. This was used to aproximate standard deviation. SPDT now uses calculated values instead.

**Comment by ccarels** [comment]
Following offline discussion, some of this code is out of date and unused, and should be removed.

**Comment by ccarels** [comment]
On cc_62_buildsystem, I have kept c_sqrt_taps and the associated kernels and code, even though they are not actually used.

**Comment by ccarels** [comment]
The question is answered and the code is refactored on cc_62_buildsystem. This issue is subsumed under #62 so I am closing this issue.
