### ISSUE TITLE
helper_cuda.h not found

### ISSUE THREAD

**Issue by KAdamek** [AstroAccelerateOrg/astro-accelerate#91]
**Issue Summary**
File "helper_cuda.h" not found. It is located in CUDA folder but it cannot be found by make.

**Steps to Reproduce**
launch setup.sh
cmake .
make

**Expected Outcome**

**Actual Outcome**

**Configuration**

**Notes**

**Comment by KAdamek** [comment]
file helper_string.h is missing as well

**Comment by ccarels** [comment]
Hi @KAdamek, have you tried `source setup.sh`? This should set the environment variable in the shell.

**Comment by KAdamek** [comment]
Yes, I have used setup.sh, before cmake. This was on Wes's PC. It might be cause by my configuration of the environment.

**Comment by ccarels** [comment]
Following offline discussion, I am closing this issue.
