### ISSUE TITLE
Cannot set CARD variable in params.h file

### ISSUE THREAD

**Issue by ccarels** [AstroAccelerateOrg/astro-accelerate#92]
**Description**
As per the readme, this variable should be set in the params.h file.

**Outcome**
Setting of CARD variable.

**Timeline**
As soon as possible.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: N/A.

Expected semantic version number increment category (Please indicate x.y.z): z.

**Notes**
N/A.

**Comment by KAdamek** [comment]
I should note that this does not need to be #defined by my opinion. It could be quite useful fot it to be a argument for AA or part of the configuration file. So one can run AA on different cards without need for recompilation.

**Comment by ccarels** [comment]
@KAdamek I agree. I created issue #105 for this, and will close this one.
